# Generated by Django 4.1.7 on 2023-03-29 19:35

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
