# Generated by Django 4.1.7 on 2023-03-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0003_alter_episode_description_alter_serie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='serie',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='actors',
            field=models.ManyToManyField(to='tv_series.actor'),
        ),
        migrations.AddField(
            model_name='serie',
            name='categories',
            field=models.ManyToManyField(to='tv_series.category'),
        ),
    ]
