# Generated by Django 4.1.7 on 2023-03-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0005_rename_category_genre_rename_categories_serie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Aktyor', 'verbose_name_plural': 'Aktyorlar'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Bölüm', 'verbose_name_plural': 'Bölümlər'},
        ),
        migrations.AlterModelOptions(
            name='episodegallery',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Janr', 'verbose_name_plural': 'Janr'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Sezon', 'verbose_name_plural': 'Sezon'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Serial', 'verbose_name_plural': 'Seriallar'},
        ),
        migrations.AlterModelOptions(
            name='seriegallery',
            options={'verbose_name': 'Şəkil', 'verbose_name_plural': 'Şəkillər'},
        ),
    ]
