# Generated by Django 4.1.7 on 2023-04-09 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tv_series', '0006_alter_actor_options_alter_episode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
