# Generated by Django 4.1.7 on 2023-04-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0007_serie_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Ölkə',
                'verbose_name_plural': 'Ölkə',
            },
        ),
        migrations.AddField(
            model_name='serie',
            name='age_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='imdb',
            field=models.FloatField(default=2.1),
        ),
        migrations.AddField(
            model_name='serie',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tv_series.country'),
        ),
    ]
