# Generated by Django 4.1.7 on 2023-04-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0008_country_serie_age_limit_serie_imdb_serie_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Dillər',
            },
        ),
        migrations.AddField(
            model_name='serie',
            name='language',
            field=models.ManyToManyField(to='tv_series.language'),
        ),
    ]
