# Generated by Django 4.1.7 on 2023-04-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0009_language_serie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tv_series.serie'),
        ),
    ]
