# Generated by Django 4.1.7 on 2023-04-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0010_episode_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tv_series.serie'),
        ),
    ]
