# Generated by Django 4.1.7 on 2023-04-11 11:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tv_series', '0012_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentepisode', ckeditor.fields.RichTextField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_series.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Bolum Comment',
            },
        ),
    ]
