# Generated by Django 4.1.7 on 2023-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0014_serie_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='watched_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
