# Generated by Django 4.1.7 on 2023-08-22 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tv_series', '0017_comment_dislikes_comment_likes_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentepisode',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='tv_episodes_disliked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentepisode',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tv_episodes_liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
