# Generated by Django 4.1.7 on 2023-08-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0019_episodereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodereview',
            options={'verbose_name': 'Epizod Reyting', 'verbose_name_plural': 'Reyting'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Serial Reyting', 'verbose_name_plural': 'Reyting'},
        ),
    ]
