# Generated by Django 4.1.7 on 2023-04-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
