# Generated by Django 4.1.7 on 2023-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='logo',
            field=models.ImageField(default='logo.jpg', upload_to='posters/'),
        ),
    ]
