# Generated by Django 4.1.7 on 2023-04-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_myuser_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='logo',
            field=models.ImageField(default='https://img.freepik.com/premium-vector/anonymous-user-circle-icon-vector-illustration-flat-style-with-long-shadow_520826-1931.jpg', upload_to='posters/'),
        ),
    ]
