# Generated by Django 4.1.7 on 2023-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_myuser_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='logo',
            field=models.ImageField(default='logo.jpeg', upload_to='posters/'),
        ),
    ]
