# Generated by Django 4.1.7 on 2023-03-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviegalleryimage_moviegalleryvideo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='categories',
            new_name='genres',
        ),
    ]
