# Generated by Django 4.1.7 on 2023-03-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_category_genre_rename_categories_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Aktyor', 'verbose_name_plural': 'Aktyorlar'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Janr', 'verbose_name_plural': 'Janr'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Filmlər'},
        ),
        migrations.AlterModelOptions(
            name='moviegalleryimage',
            options={'verbose_name': 'Şəkil', 'verbose_name_plural': 'Şəkillər'},
        ),
        migrations.AlterModelOptions(
            name='moviegalleryvideo',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
    ]
