# Generated by Django 4.1.7 on 2023-04-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_newmovies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newmovies',
            options={'verbose_name': 'Gələcək Filmlər', 'verbose_name_plural': 'Gələcək Filmlər'},
        ),
    ]
