# Generated by Django 4.1.7 on 2023-04-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_newmovies_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewMovies',
            new_name='ComingMovie',
        ),
    ]
