# Generated by Django 4.1.7 on 2023-04-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_rename_newmovies_comingmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_limit',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
