# Generated by Django 4.1.7 on 2023-04-08 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
