# Generated by Django 4.1.7 on 2023-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_movie_watched_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='account',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], default='Basic', max_length=30),
        ),
    ]
