# Generated by Django 4.1.7 on 2023-08-10 14:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor.fields.RichTextField(default='null'),
        ),
    ]
