# Generated by Django 4.1.7 on 2023-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
